### PR TITLE
NullPointerException fixes and overridden clear() for convenience

### LINKED ISSUE #26: null focusable actor causes nullpointer exception isActorFocusable
As title says. When an actor that is in the focusableActors array becomes null it will crash with a nullpointer exception rather than just return false and possibly remove it from the array.

Exception in thread "main" java.lang.NullPointerException
	at de.golfgl.gdx.controllers.ControllerMenuStage.isActorFocusable(ControllerMenuStage.java:202)

While I am at it. addFocusableActor(Actor actor) also allows null to be put in causing the exception as well when you want to focus on it. Perhaps a null check needs to be added there as well?

### PR DESCRIPTION
**Pull request by Azania**
This will fix issue #26 with the null pointer exceptions.
Added a commit that override clear() as clear without clearing focusable actors could also lead to issues and imho should clear should clear all including the focusable actors array and selected.

### CODE REVIEW

File: core-scene2d/src/de/golfgl/gdx/controllers/ControllerMenuStage.java [hunk 1]
```diff
@@ -103,7 +114,7 @@ public void clearFocusableActors() {
      */
     public void removeFocusableActorsNotOnStage() {
         for (int i = focusableActors.size - 1; i >= 0; i--) {
-            if (focusableActors.get(i).getStage() != this)
+            if (focusableActors.get(i) == null || focusableActors.get(i).getStage() != this)
```
Comment (MrStahlfelge) [inline core-scene2d/src/de/golfgl/gdx/controllers/ControllerMenuStage.java:117]: I wonder how there can be null-entries in the array? Maybe this is obsolete when we have the null check on addFocusableActor?

Comment (Azania) [reply core-scene2d/src/de/golfgl/gdx/controllers/ControllerMenuStage.java:117]: You can still modify actors while they are in the array and make em null. Which means later when you call that method you get a nullpointer exception, this will still remove it without causing the exception. It would be bad design but it is a fail safe. I could not find other places where it could potential crash with a nullpointer exception. You could leave it out but I learned that some people make some crazy at times. Better safe than sorry imho

Edit: you can still do anything you want with the array when you call getFocusableActors(). like .set(0, null); e.g.
Edit2: you can also add actors (and null values even by accident) with getFocusableActors().add(actor) ..
